### PR TITLE
ipam.Prefixes.__str__ should return display attribute when prefixes attribute is missing

### PR DESCRIPTION
**Pull request by thatfatguypat**
Addresses https://github.com/nautobot/pynautobot/issues/53

### CODE REVIEW

**Review by glennmatthews — COMMENTED** [review]
It would *probably* be okay to just return `self.display` in all cases, but I'm OK with this more cautious approach.

Is `prefixes.tags` the only endpoint that shows this issue, or is this a general problem with any `Record` subclass that defines a custom `__str__` method - for example, is a similar fix needed on `IpAddresses`, above?

**Comment by glennmatthews** [comment]
See my comment on #53 - I still think this change is valid in and of itself, but I don't believe it addresses the actual underlying issue, which may be a regression introduced by #41.

**Comment by jmcgill298** [comment]
The issue seems to be what class is being used to generate the value(s) for attributes that are instances of another Nautobot object (Record classes in pynautobot). I put a different type of patch together in #55

**Comment by thatfatguypat** [comment]
> Is prefixes.tags the only endpoint that shows this issue, or is this a general problem with any Record subclass that defines a custom __str__ method - for example, is a similar fix needed on IpAddresses, above?

As of yet, I've only been able to repro the issue with prefixes.tags

> I still think this change is valid in and of itself, but I don't believe it addresses the actual underlying issue, which may be a regression introduced by https://github.com/nautobot/pynautobot/pull/41.

@glennmatthews that's a fair assessment.  It very well may mean that I'm addressing a symptom, rather than the cause.  If that is the case, shall I close this out in preference for #53 or #55?

**Comment by glennmatthews** [comment]
> > I still think this change is valid in and of itself, but I don't believe it addresses the actual underlying issue, which may be a regression introduced by #41.
> 
> @glennmatthews that's a fair assessment. It very well may mean that I'm addressing a symptom, rather than the cause. If that is the case, shall I close this out in preference for #53 or #55?

Let's keep this open for now - we're having some team discussions and investigation around #53 and #41 to figure out the best way forward.

**Comment by thatfatguypat** [comment]
Closing this now that #57 has been merged and addresses Issue #53

**Pull request closed without merging**
