### PR TITLE
Release 2.0

### PR DESCRIPTION
**Pull request by pszulczewski**
Updates for release 2.0.
`develop` has been merged into `next-2.0`

### CODE REVIEW

**Comment by pszulczewski** [comment]
@jvanderaa just to confirm, `next-2.0` goes to `main` ?

**Comment by joewesch** [comment]
That's a good question. Are we going to maintain a "main" for 4.x bug fixes to follow with Nautobot 1.6 LTM?

**Comment by pszulczewski** [comment]
From `App & SDK Branching Strategy`:
```
* ltm-1.6 is created from main - bugfix branch for LTM compatible releases
* next-2.0 is frozen and merged into develop
* develop now tracks Nautobot 2.x
* releases are created from develop and merged into main as usual. main now tracks Nautobot 2.x
* next-3.0 eventually tracks Nautobot 3.0 (pre-release)
```

**Comment by pszulczewski** [comment]
`ltm-1.6` has been checked out from `main`, nautobot `"stable"` changed to `"1.6"`, python 3.7 removed. `origin/develop` merged into `ltm0-1.6` as we didn't have all commits in main.
We should be good now.

**Review by joewesch — APPROVED** [review]

**Pull request merged**
