### PR TITLE
Resolves #71 - updating to account for json type custom field

### LINKED ISSUE #71: JSON CustomField Type unable to serialize Dictionary
Nautobot: 1.3.9 -1.4.1
pynautobot: 1.1.2
Python: 3.8

Observed Behavior:
- In nautobot 1.3 JSON field type was introduced as an option for CustomFields. This field is set as a pythonic representation of JSON in the UI view.
- If a custom field is created as a JSON type AND the value of the custom field is a dictionary a ValueError is raised for trying to unpack value as a key in the dictionary when calling serialize from PyNautobot on an instance of a device object.

Expected Behavior:
- PyNautobot able to serialize a JSON type custom field.

### PR DESCRIPTION
**Pull request by whitej6**
I need someone with prior knowledge on this SDK to confirm we no longer need this function. as my local testing with nautobot v1.4.1 I cannot get that function to be triggered.

### CODE REVIEW

**Comment by glennmatthews** [comment]
Looking at the changed test, can we confirm that it still works with select/multi-select custom fields?

**Comment by whitej6** [comment]
@glennmatthews I will look into that, I was wondering how/where that came into play.

**Comment by whitej6** [comment]
@glennmatthews Here is an output of a JSON, text, select & multi-select CF on one device

```python
In [1]: import pynautobot

In [2]: nautobot = pynautobot.api(url="https://nautobot.whitej6.com", token="0123456789abcdef0123456789abcdef01234567")

In [3]: device = nautobot.dcim.devices.all()[0]

In [4]: device.custom_fields
Out[4]: 
{'json_test': {'bar': 'baz', 'foo': 1},
 'multi_select': ['bar', 'baz'],
 'non_json': 'i am not json',
 'select': 'bar'}

In [5]: device.serialize()
Out[5]: 
{'id': '814b329b-970b-4fc5-b688-52a0db6a7839',
 'display': 'DFW-WAN00',
 'url': 'https://nautobot.whitej6.com/api/dcim/devices/814b329b-970b-4fc5-b688-52a0db6a7839/',
 'name': 'DFW-WAN00',
 'device_type': '2194fdb7-1bb3-4419-a78e-690607a04f4d',
 'device_role': '637f1db1-1656-4ebd-813c-0cf0f22d1747',
 'tenant': None,
 'platform': '76748b6b-6e3b-4a51-b998-df468031ec37',
 'serial': '',
 'asset_tag': None,
 'site': 'b3186e80-fc91-4f28-9674-d030cbc96865',
 'location': None,
 'rack': None,
 'position': None,
 'face': None,
 'parent_device': None,
 'status': 'active',
 'primary_ip': None,
 'primary_ip4': None,
 'primary_ip6': None,
 'secrets_group': None,
 'cluster': None,
 'virtual_chassis': None,
 'vc_position': None,
 'vc_priority': None,
 'comments': '',
 'local_context_schema': None,
 'local_context_data': None,
 'config_context': {},
 'created': '2022-08-29',
 'last_updated': '2022-08-29T19:33:01.960120Z',
 'tags': [],
 'notes_url': 'https://nautobot.whitej6.com/api/dcim/devices/814b329b-970b-4fc5-b688-52a0db6a7839/notes/',
 'custom_fields': {'json_test': {'bar': 'baz', 'foo': 1},
  'multi_select': ['bar', 'baz'],
  'non_json': 'i am not json',
  'select': 'bar'}}

```

**Review by jvanderaa — APPROVED** [review]
Can we add your custom field manual testing as unit tests here?

**Pull request merged**
