### PR TITLE
Release 1.0.2

### PR DESCRIPTION
**Pull request by jvanderaa**
- Updates patch release for bug fix

### CODE REVIEW

**Comment by FragmentedPacket** [comment]
How do we want to handle changelog stuff for new releases?

**Comment by jvanderaa** [comment]
I checked into this. The CHANGELOG.md indicates to check GH Releases.

**Comment by FragmentedPacket** [comment]
Yes sorry I should have been more explicit. It appears we haven't released on Github so no history of the two other releases.

Do we want to continue the pattern of documenting in the releases?

**Comment by jvanderaa** [comment]
Per our conversation, I'll make an update to the changelog. This will benefit those that wish to view the changelog from the repo without having to look at the UI of GH

**Review by FragmentedPacket — APPROVED** [review]

**Pull request merged**
