### PR TITLE
New Release

### PR DESCRIPTION
**Pull request by jvanderaa**

### CODE REVIEW

**Comment by jvanderaa** [comment]
Need to get a CHANGELOG record in.

**Comment by jvanderaa** [comment]
Hold on merging until #97 is completed and included. This should be a minor release with the work done by @chadell

**Comment by joewesch** [comment]
@jvanderaa are we still waiting on something for this except for review by @jmcgill298?

**Comment by jvanderaa** [comment]
Let's do this today regardless. I'm hoping that we can get #56 across the finish line and included. But we should just get the new release out.

**Comment by jvanderaa** [comment]
Let's' get this out, we can do another release. If you approve I'll get @jmcgill298 to put a check on it too.

**Review by joewesch — APPROVED** [review]

**Review by jmcgill298 — APPROVED** [review]

**Pull request merged**
